import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div
					className="mx-auto grid h-full min-h-screen"
					style={{
						gridTemplateColumns: "100%",
						gridTemplateRows: "auto 1fr auto",
					}}
				>
					<header className="container sticky top-0 z-40 bg-white mx-auto">
						<div className="h-16 border-b border-b-slate-200 py-4">
							<nav className="ml-4 pl-6">
								<a href="#" className="hover:text-slate-600 cursor-pointer">
									Home
								</a>
							</nav>
						</div>
					</header>
					<main className="flex w-full h-full flex-1 flex-col overflow-hidden">
						{children}
					</main>
					<footer className="m-auto p-4">Powered by LangChainAI.</footer>
				</div>
			</body>
		</html>
	);
}
