name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3
    - name: Utiliser Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installer les dépendances
      run: npm --prefix backend install
    - name: Linter le code
      run: npm --prefix backend run lint
    - name: Formater le code
      run: npm --prefix backend run format
    # - name: Exécuter les tests
    #   run: npm test

